name: Suggestion
description: Give a suggestion for the game.
title: "[Suggestion]: "
labels: ["suggestion"]
assignees:
  - dainfloop
body:
  - type: markdown
    attributes:
      value: |
        Have a suggestion for the game, whether it be a new character, new song or new anything, here's the place to be!
        (Anything wrapped in < !-- -->, you will only see.)
  - type: dropdown
    id: type
    attributes: 
      label: |
        What type of suggestion is this?
        <!-- Game means anything that isn't already on the dropdown. Note: custom weeks will not be added, but you can fork this if you want and edit it! -->
      multiple: false
      options:
        - Game
        - Song
        - New Character
    validations:
      required: true
  - type: textarea
    id: explain
    attributes:
      label: Expand on what your suggestion is.
      placeholder: |
        Ex. When all the erect remixes come out, I think they should be added to the game
    validations:
      required: true
  - type: checkboxes
    id: checked
    attributes:
      label: Have you checked your suggestion hasn't been posted by anyone else?
      options:
        - label: I have checked no one has posted my suggestion, and that my suggestion is unique!
          required: true